### ISSUE TITLE
Add instructions/link to fix missing user info issue in get_user_info function in tools.py

### ISSUE THREAD

**Issue by yucongalicechen** [diffpy/diffpy.utils#129]
### Problem

Instructions for getting user info can be clearer. Right now there are no instructions in the warning message on how to fix missing user info.

### Proposed solution
Edit messages in `get_user_info` function in `tools.py`. Specifically, include instructions in the warning message and/or include a link to the right place in the online docs for fixing missing user info issue.
For more details, see discussions in https://github.com/diffpy/diffpy.labpdfproc/issues/113.

**Comment by sbillinge** [comment]
further to this...the current behavior is good (warning but not error if name is missing). The problem is that there are no instructions in the warning how to fix the issue.  There are instructions in diffpy.utils documentation, but we ran into the  problem that this warning popped up when `diffpy.labpdfproc` was being run, and there is no way that the user would know to look in the online docs for diffpy.utils.....

fix: include instructions in the warning message itself (if they are short enough) and/or include a link to the right place in the online docs for how to fix it.
