### ISSUE TITLE
Add an option to automatically interpolate onto the Nyquist grid into wsinterp

### ISSUE THREAD

**Issue by Sparks29032** [diffpy/diffpy.utils#145]
This would be put into `diffpy.utils.parsers.resample`. Also good to think about reorganizing to `diffpy.utils.resample` without the parsers for this functionality. Might have to change some paths.

**Comment by Sparks29032** [comment]
I don't think that resample is being used. However, to be safe, for this release, add a deprecation warning at the top of the old resample. Then on the next release we can remove the function.

**Comment by Sparks29032** [comment]
Raising the warning.

**Comment by bobleesj** [comment]
@Sparks29032 @sbillinge since this was under `3.6.0` release, I am trying to understand what needs to be done.

 Could you please explain what `interpolate onto the Nyquist grid into wsinterp ` this means? Since this issue was written back then and deviates from our current GitHub Issues template, I am not sure what problem this issue solves and how to solve. 

Seems to be related to the following issue: https://github.com/diffpy/diffpy.utils/issues/48 by @sbillinge

**Comment by Sparks29032** [comment]
I'll submit a PR on this Saturday. A bit busy right now.

**Comment by bobleesj** [comment]
Thanks! @Sparks29032

**Comment by bobleesj** [comment]
@Sparks29032 double checking - does this PR https://github.com/diffpy/diffpy.utils/pull/235 close this issue as well?

**Comment by Sparks29032** [comment]
Yes.
