### ISSUE TITLE
Do not allow an empty instance of `DiffractionObject` - init requires `xarray`, `yarray`, `xtype`

### ISSUE THREAD

**Issue by bobleesj** [diffpy/diffpy.utils#227]
### Problem

Continuing our discussion from https://github.com/diffpy/diffpy.utils/issues/224 - We do not want User to have an empty `DiffractionObject` instance. 

### Proposed solution

In our `init` method, we could modfy

from:

```python
class DiffractionObject:
    def input_data(
        self,
        xarray,
        yarray,
        xtype,
        metadata={},
        scat_quantity=None,
        name=None,
        wavelength=None,
    ):

```

to: 

```python
class DiffractionObject:
    def __init__(
        self,
        xarray,
        yarray,
        xtype,
        wavelength,
        scat_quantity="",
        name="",
        metadata={},
    ):

        self._id = uuid.uuid4()
        self.input_data(xarray, yarray, xtype, wavelength, scat_quantity, name, metadata)
```

Here, User needs to provide `xarray`, `yarray`, `xtype` and `wavelength`. Here, `xtype` and `wavelneght` are required for  the ` self._set_xarrays(xarray, xtype)` method within `input_data ` where we utilize `self.wavelength` and `self.xtype` as shown below:

```python
    def _set_xarrays(self, xarray, xtype):
        self._all_arrays = np.empty(shape=(len(xarray), 4))
        if xtype.lower() in QQUANTITIES:
            self._all_arrays[:, 1] = xarray
            self._all_arrays[:, 2] = q_to_tth(xarray, self.wavelength)
            self._all_arrays[:, 3] = q_to_d(xarray)
    ....
```

@sbillinge I have a draft PR here: https://github.com/diffpy/diffpy.utils/pull/228 for this implementation.

**Comment by sbillinge** [comment]
I think that's about right, and I think we want `input_arrays` to be private. 

We don't want wavelength required though. Set default to none. I think we handle that in thighs arrays. Also, pretty soon Caden will need tof neutron data in the DO and then angle is fixed and lamba is in the array....

Actually, kind of interestingly, because he has lots of detectors, angle and wavelength could both be arrays.  Let's leave that for a nice future project for Caden, but for now make wavelength optional.
